baseURL = "/"
languageCode = "en-us"
title = "Mattia"

theme="hugo-paper"

enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[params]
  color = 'linen'                           # linen, wheat, gray, light

  github = 'maettu999'                 # github.com/YOUR_GITHUB_ID
  instagram = 'mattia.05x'           # instagram.com/YOUR_INSTAGRAM_ID

  avatar = 'mattia.gisiger@gmail.com'                 # gravatar email or image url
  name = 'Mattia'
  bio = 'i like sports and coding'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
